import React, { useState, useEffect, useRef } from 'react';
import axios from './api';
import * as XLSX from 'xlsx';
import {
  Button,
  Card,
  Form,
  Input,
  Select,
  Table,
  Space,
  Typography,
  Divider,
  Row,
  Col,
  message,
  Tag,
  Tooltip,
  Modal,
  Spin,
  Alert
} from 'antd';
import {
  PlusOutlined,
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  UserOutlined,
  CloseOutlined,
  SaveOutlined,
  ExclamationCircleOutlined,
  InboxOutlined,
  DownloadOutlined,
  ImportOutlined,
  UserSwitchOutlined
} from '@ant-design/icons';

import { PageHeader, ControlPanel, CustomerForm } from './components/CustomerScreenComponents';

// Assuming this interface is defined in './services/mockApi' or a shared types file
// I'm defining it here for clarity, please ensure your actual CustomerData matches this.
export interface CustomerData {
  id: string; // Assuming 'id' is generated by backend
  name: string;
  address: string;
  city: string;
  district: string;
  state: string;
  postalCode: string;
  landmark: string;
  phone: string; // Maps to 'MOBILE NO.' or 'MOBILE NO. 1'
  mobileNumber2: string; // Maps to 'MOBILE NO. 2'
  source: string;
  createdAt?: string;
}


// Helper function to standardize state names
const standardizeState = (state: string) => {
  if (!state) return '';
  return state
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};

// Helper function to normalize customer data from different sources
const normalizeCustomerData = (customer: any): CustomerData => {
  return {
    id: customer.id || Date.now().toString() + Math.random(), // Ensure ID exists
    name: customer.name || customer.customerName || '',
    address: customer.address || customer.billingAddress || '',
    city: customer.city || '',
    district: customer.district || '',
    state: standardizeState(customer.state || ''),
    postalCode: customer.postalCode || customer.pinCode || '',
    landmark: customer.landmark || '',
    phone: customer.phone || customer.mobileNumber1 || '',
    mobileNumber2: customer.mobileNumber2 || '',
    source: customer.source || '',
    createdAt: customer.createdAt || new Date().toISOString(),
  };
};

// Initial form data - ALIGNED WITH CustomerData INTERFACE
const initialFormData: Omit<CustomerData, 'id'> = {
  name: '',
  address: '',
  city: '',
  district: '',
  state: '',
  postalCode: '',
  landmark: '',
  phone: '',
  mobileNumber2: '',
  source: ''
};

const CustomerScreen = () => {
  const [customers, setCustomers] = useState<CustomerData[]>([]);
  const [filteredCustomers, setFilteredCustomers] = useState<CustomerData[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<CustomerData | null>(null);
  const [showImportModal, setShowImportModal] = useState(false);
  const [showUpdateModal, setShowUpdateModal] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [form] = Form.useForm();
  const [tableParams, setTableParams] = useState({
    pagination: {
      current: 1,
      pageSize: 10,
      showSizeChanger: true,
      pageSizeOptions: [10, 20, 50, 100, 500, 1000, 2000, 5000],
    },
  });

  useEffect(() => {
    fetchCustomers();

    const handleAuthError = () => {
      window.dispatchEvent(new CustomEvent('authRefresh'));
    };

    const handleCustomersUpdated = () => {
      fetchCustomers();
    };

    window.addEventListener('authError', handleAuthError);
    window.addEventListener('customersUpdated', handleCustomersUpdated);

    return () => {
      window.removeEventListener('authError', handleAuthError);
      window.removeEventListener('customersUpdated', handleCustomersUpdated);
    };
  }, []);

  useEffect(() => {
    console.log(`useEffect triggered: searchTerm="${searchTerm}", customers.length=${customers.length}`);
    
    if (searchTerm === '') {
      console.log('No search term, showing all customers');
      setFilteredCustomers(customers);
    } else {
      const term = searchTerm.toLowerCase();
      console.log(`Filtering customers with term: "${term}"`);
      
      const filtered = customers.filter(customer => {
        const nameMatch = customer.name && customer.name.toLowerCase().includes(term);
        const phoneMatch = customer.phone && customer.phone.includes(term);
        const cityMatch = customer.city && customer.city.toLowerCase().includes(term);
        const stateMatch = customer.state && customer.state.toLowerCase().includes(term);
        
        return nameMatch || phoneMatch || cityMatch || stateMatch;
      });
      
      console.log(`Filtered to ${filtered.length} customers`);
      setFilteredCustomers(filtered);
    }
  }, [searchTerm, customers]);

  const fetchCustomers = async () => {
    setIsLoading(true);
    console.log('Attempting to fetch customers from localStorage...');
    
    const localCustomersRaw = localStorage.getItem('customers');
    if (localCustomersRaw) {
      try {
        const localCustomers = JSON.parse(localCustomersRaw).map(normalizeCustomerData);
        setCustomers(localCustomers);
        setFilteredCustomers(localCustomers);
      } catch (e) {
        console.error("Error parsing customers from localStorage", e);
        setCustomers([]);
        setFilteredCustomers([]);
      }
    } else {
      setCustomers([]);
      setFilteredCustomers([]);
    }
    setIsLoading(false);
  };

  // Type for values received from Ant Design Form
  interface FormValues extends Omit<CustomerData, 'id'> {}

  const handleSubmit = async (values: FormValues) => {
    setSaveError(null);
    setIsSaving(true);

    try {
      const normalizedData = {
        ...values,
        state: standardizeState(values.state),
      };

      let updatedCustomers;

      if (editingCustomer) {
        // Update existing customer locally
        console.log("Local mode: updating customer locally.");
        const updatedCustomer = { ...editingCustomer, ...normalizedData };
        updatedCustomers = customers.map(c => c.id === editingCustomer.id ? updatedCustomer : c);
        message.success('Customer updated successfully!');
      } else {
        // Create new customer
        const isDuplicate = customers.some(
          (customer) =>
            customer.name &&
            normalizedData.name &&
            customer.name.toLowerCase() === normalizedData.name.toLowerCase() &&
            customer.phone === normalizedData.phone
        );

        if (isDuplicate) {
          alert('A customer with this name and mobile number already exists!');
          setIsSaving(false);
          return;
        }

        // Create new customer locally
        console.log("Local mode: creating customer locally.");
        const newCustomer: CustomerData = {
          ...normalizedData,
          id: 'local-' + Date.now().toString(), // Create a temporary local ID
          createdAt: new Date().toISOString(),
        };
        updatedCustomers = [...customers, newCustomer];
        message.success('Customer added successfully!');
      }

      localStorage.setItem('customers', JSON.stringify(updatedCustomers));
      window.dispatchEvent(new Event('customersUpdated')); // Notify other components
      setCustomers(updatedCustomers);
      setFilteredCustomers(updatedCustomers);
      resetForm();
    } catch (err: any) {
      console.error('Error saving customer:', err);
      const errorMessage =
        err.message ||
        'Failed to save customer. Please try again.';
      setSaveError(errorMessage);
      alert(`Error: ${errorMessage}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleEdit = (customer: CustomerData) => {
    setEditingCustomer(customer);
    form.setFieldsValue({
      ...customer,
      state: standardizeState(customer.state),
    });
    setShowAddForm(true);
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('Are you sure you want to delete this customer?')) {
      try {
        const updatedCustomers = customers.filter((customer) => customer.id !== id);
        localStorage.setItem('customers', JSON.stringify(updatedCustomers));
        window.dispatchEvent(new Event('customersUpdated'));
        setCustomers(updatedCustomers);
        message.success('Customer has been deleted.');
      } catch (err: any) {
        console.error('Error deleting customer:', err);
        message.error('Failed to delete customer.');
      }
    }
  };

  const handleImport = async () => {
    if (!selectedFile) {
      message.error('Please select a file to import.');
      return;
    }

    setIsImporting(true);

    try {
      const data = await selectedFile.arrayBuffer();
      const workbook = XLSX.read(data, { type: 'array' });
      const worksheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[worksheetName];
      const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: '' }) as any[][];

      if (!jsonData || jsonData.length < 2) {
        message.warning('No data found in the Excel file.');
        setIsImporting(false);
        return;
      }

      const rawHeaders = jsonData[0] as string[];
      const headers = rawHeaders.map(h => (h ? h.toString().trim().toUpperCase() : ''));
      const rows = jsonData.slice(1);

      const getColIndex = (keyword: string) => headers.findIndex(h => h.includes(keyword.toUpperCase()));

      const nameIndex = getColIndex('CUSTOMER NAME');
      const addressIndex = getColIndex('HOUSE NO./ FLAT NO./ STREET NO.');
      const cityIndex = getColIndex('CITY/TOWN/VILLAGE');
      const districtIndex = getColIndex('P.O/DISTRICT');
      const stateIndex = getColIndex('STATE');
      const postalCodeIndex = getColIndex('PIN CODE');
      const landmarkIndex = getColIndex('LANDMARK');
      const mobile1Index = getColIndex('MOBILE NO.');
      const mobile2Index = headers.findIndex((h, idx) => idx > mobile1Index && h.includes('MOBILE NO. 2'));
      const sourceIndex = getColIndex('SOURCE');

      if (nameIndex === -1 || mobile1Index === -1) {
        message.error('Required columns (CUSTOMER NAME and MOBILE NO.) not found in the Excel file.');
        setIsImporting(false);
        return;
      }

      const customersToImport = rows
        .map((row, rowIndex) => {
          const getCellValue = (index: number, defaultValue = '') => {
            if (index === -1 || !row || row[index] === undefined) {
              return defaultValue;
            }
            return String(row[index]).trim();
          };

          return {
            id: Date.now().toString() + rowIndex,
            createdAt: new Date().toISOString(),
            name: getCellValue(nameIndex),
            phone: getCellValue(mobile1Index),
            address: getCellValue(addressIndex),
            city: getCellValue(cityIndex),
            district: getCellValue(districtIndex),
            state: getCellValue(stateIndex),
            postalCode: getCellValue(postalCodeIndex),
            landmark: getCellValue(landmarkIndex),
            mobileNumber2: getCellValue(mobile2Index),
            source: getCellValue(sourceIndex),
          };
        })
        .filter(customer => customer.name && customer.phone);

      if (customersToImport.length === 0) {
        message.warning('No valid customer data found in the file.');
        setIsImporting(false);
        return;
      }

      const existingCustomers = JSON.parse(localStorage.getItem('customers') || '[]');
      const mergedCustomers = [...existingCustomers];
      let importedCount = 0;

      customersToImport.forEach(newCustomer => {
        const isDuplicate = existingCustomers.some(
          (existing) =>
            existing.name.toLowerCase() === newCustomer.name.toLowerCase() &&
            existing.phone === newCustomer.phone
        );

        if (!isDuplicate) {
          mergedCustomers.push(newCustomer);
          importedCount++;
        }
      });

      localStorage.setItem('customers', JSON.stringify(mergedCustomers));
      setCustomers(mergedCustomers);
      setFilteredCustomers(mergedCustomers);

      message.success(`Successfully imported ${importedCount} new customers.`);
      setShowImportModal(false);
    } catch (error) {
      console.error('Error importing customers:', error);
      message.error('Failed to import customers. Please check the file and try again.');
    } finally {
      setIsImporting(false);
    }
  };

  // ======================================================================
  // handleUpdateCustomers FUNCTION
  // ======================================================================
  const handleUpdateCustomers = async () => {
    if (!selectedFile) {
      message.warning('Please select a file first');
      return;
    }

    console.log('Starting update process with file:', selectedFile.name);
    setIsImporting(true);

    try {
      const data = await selectedFile.arrayBuffer();
      const workbook = XLSX.read(data, { type: 'array' });
      const worksheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[worksheetName];
      const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: '' }) as any[][];

      if (!jsonData || jsonData.length < 2) {
        message.warning('No data found in the Excel file or file contains only headers.');
        setIsImporting(false);
        return;
      }

      const rawHeaders = jsonData[0] as string[];
      const clean = (text = '') => text.replace(/\s+/g, ' ').replace(/[\u200B-\u200D\uFEFF]/g, '').trim().toUpperCase();
      const headers = rawHeaders.map(h => clean(h));
      console.log('Detected headers:', headers);
      const rows = jsonData.slice(1);
      
      // Fix merged DISTRICT+STATE columns
      for (let i = 0; i < headers.length; i++) {
        if (headers[i].includes('P.O/DISTRICT STATE')) {
          headers[i] = 'P.O/DISTRICT';
          headers.splice(i + 1, 0, 'STATE');
          rows.forEach(row => {
            const cellValue = row[i] || '';
            const parts = cellValue.split(' ');
            row[i] = parts.slice(0, -1).join(' ');
            row.splice(i + 1, 0, parts.slice(-1)[0] || '');
          });
          break;
        }
      }

      const getColIndex = (keyword: string) => headers.findIndex(h => h.includes(keyword.toUpperCase()));

      const nameIndex = getColIndex('CUSTOMER NAME');
      const addressIndex = getColIndex('HOUSE NO./ FLAT NO./ STREET NO.');
      const cityIndex = getColIndex('CITY/TOWN/VILLAGE');
      const districtIndex = getColIndex('P.O/DISTRICT');
      const stateIndex = getColIndex('STATE');
      const postalCodeIndex = getColIndex('PIN CODE');
      const landmarkIndex = getColIndex('LANDMARK');
      const mobile1Index = getColIndex('MOBILE NO.');
      let mobile2Index = -1;
      if (mobile1Index !== -1) {
          mobile2Index = headers.findIndex((h, idx) => idx > mobile1Index && h.includes('MOBILE NO. 2'.toUpperCase()));
          if (mobile2Index === -1) {
              mobile2Index = headers.findIndex((h, idx) => idx > mobile1Index && h.includes('MOBI'));
          }
      }
      const sourceIndex = getColIndex('SOURCE');
      
      if (mobile1Index === -1) {
        message.error('Required column (MOBILE NO.) not found in the Excel file for updating customers.');
        setIsImporting(false);
        return;
      }

      // Debug: Log the rows data
      console.log('Rows data:', rows);
      console.log('Column indices:', {
        nameIndex,
        addressIndex,
        cityIndex,
        districtIndex,
        stateIndex,
        postalCodeIndex,
        landmarkIndex,
        mobile1Index,
        mobile2Index,
        sourceIndex
      });
      
      const customersToUpdate = rows
        .filter(row => {
          const isRowEmpty = !row || row.length === 0 || !row.some(cell => cell !== undefined && cell !== '');
          return !isRowEmpty;
        })
        .map((row, rowIndex) => {
          const getCellValue = (index: number, defaultValue: string = '') => {
            if (index === -1 || !row || row[index] === undefined) {
              return defaultValue;
            }
            return String(row[index]).trim();
          };

          const customer = {
            name: getCellValue(nameIndex),
            phone: getCellValue(mobile1Index), // This will be used to match existing customers
            address: getCellValue(addressIndex),
            city: getCellValue(cityIndex),
            district: getCellValue(districtIndex),
            state: getCellValue(stateIndex),
            postalCode: getCellValue(postalCodeIndex),
            landmark: getCellValue(landmarkIndex),
            mobileNumber2: getCellValue(mobile2Index),
            source: getCellValue(sourceIndex)
          };
          
          // Debug: Log each customer being processed
          console.log(`Processing row ${rowIndex}:`, row, '→', customer);
          
          return customer;
        })
        .filter(customer => customer.phone); // Only update customers with a mobile number
        
      // Debug: Log the final customersToUpdate array
      console.log('Final customers to update:', customersToUpdate);

      if (customersToUpdate.length === 0) {
        message.warning('No valid customer data with mobile numbers found in the file for updating.');
        setIsImporting(false);
        return;
      }

      // Debug: Log the data being sent
      console.log('Attempting to update customers:', customersToUpdate);
      
      // Always save to localStorage first for immediate UI update
      const existingCustomers = JSON.parse(localStorage.getItem('customers') || '[]');
      let updatedCount = 0;
      
      // Create a map of existing customers by phone for faster lookup
      const customerMap = new Map();
      existingCustomers.forEach((customer: any) => {
        if (customer.phone) {
          customerMap.set(customer.phone, customer);
        }
      });
      
      // Update existing customers or add new ones
      customersToUpdate.forEach(newCustomer => {
        if (newCustomer.phone) {
          const existingCustomer = customerMap.get(newCustomer.phone);
          if (existingCustomer) {
            // Update existing customer
            Object.assign(existingCustomer, newCustomer);
            updatedCount++;
          } else {
            // Add new customer
            const newCustomerWithId = { ...newCustomer, id: Date.now().toString() + Math.random().toString(36).substr(2, 9) };
            existingCustomers.push(newCustomerWithId);
            updatedCount++;
          }
        }
      });
      
      // Save to localStorage
      localStorage.setItem('customers', JSON.stringify(existingCustomers));
      
      // Update state immediately for instant UI update
      setCustomers(existingCustomers);
      setFilteredCustomers(existingCustomers);
      
      console.log(`Updated ${updatedCount} customers in localStorage`);
      
      // Try to send the data to the backend for bulk update (but don't wait for it)
      axios.post('/customers/bulk-update', customersToUpdate, {
        headers: {
          'Content-Type': 'application/json'
        },
        timeout: 5000 // 5 second timeout
      })
      .then(response => {
        if (response.status === 200 || response.status === 201) {
          console.log(`Backend update successful: ${response.data.updatedCount || 0} customers.`);
          // No need to update UI again since we already did it above
        }
      })
      .catch(apiError => {
        console.warn('API update failed (but localStorage was already updated):', apiError);
        // No need to show error message since we already saved to localStorage
      });
      
      // Show success message immediately
      message.success(`Successfully updated ${updatedCount} customers.`);

      setShowUpdateModal(false);
      setSelectedFile(null);
    } catch (error: any) {
      console.error('Error updating customers:', error);
      message.error(`Failed to update customers: ${error.response?.data?.message || error.message || 'Unknown error'}`);
    } finally {
      setIsImporting(false);
    }
  };
  // ======================================================================
  // END handleUpdateCustomers FUNCTION
  // ======================================================================

  const resetForm = () => {
    form.resetFields();
    setEditingCustomer(null);
    setShowAddForm(false);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setSelectedFile(file);
  };

  // ======================================================================
  // REWRITTEN AND FIXED handleImportCustomers FUNCTION
  // ======================================================================
  const handleImportCustomers = async () => {
    if (!selectedFile) {
      message.warning('Please select a file first');
      return;
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 p-4 sm:p-8">
      <div className="container mx-auto">
        <div className="bg-white rounded-2xl shadow-xl p-4 sm:p-6 lg:p-8">
          <PageHeader title="Customer Management" subtitle="Manage your customer database" />

          <ControlPanel
            showAddForm={showAddForm}
            onAddClick={() => setShowAddForm(!showAddForm)}
            onUpdateClick={() => {
              const localData = localStorage.getItem('customers');
              const customerCount = localData ? JSON.parse(localData).length : 0;
              console.log(`--- DEBUG: localStorage 'customers' count ---`);
              console.log(`${customerCount} customers found.`);
              console.log("------------------------------------");
              message.info(`${customerCount} customers found in local storage.`);
              setShowUpdateModal(true)
            }}
            searchTerm={searchTerm}
            onSearchChange={(e) => setSearchTerm(e.target.value || '')}
            onDebugClick={() => {
              const localData = localStorage.getItem('customers');
              console.log("--- DEBUG: localStorage 'customers' ---");
              if (localData) {
                try {
                  console.log(JSON.parse(localData));
                } catch (e) {
                  console.log("Could not parse JSON, showing raw data:");
                  console.log(localData);
                }
              } else {
                console.log("No 'customers' item found in localStorage.");
              }
              console.log("------------------------------------");
              message.info('LocalStorage content logged to developer console (F12)');
            }}
          />

          {/* Add/Edit Customer Form */}
          <Modal
            title={editingCustomer ? 'Edit Customer' : 'Add New Customer'}
            open={showAddForm}
            onCancel={resetForm}
            footer={null}
            width={800}
            draggable
          >
            {showAddForm && (
              <CustomerForm
                form={form}
                editingCustomer={editingCustomer}
                isSaving={isSaving}
                saveError={saveError}
                onFinish={handleSubmit}
                onCancel={resetForm}
              />
            )}
          </Modal>

          {/* The old search bar is now removed as it's integrated into the control panel above */}

          {/* Customer List */}
          <div className="mb-4 flex justify-between items-center">
            <div>
              {isLoading ? (
                <Spin size="small" tip="Loading customers..." />
              ) : (
                <span>Showing {filteredCustomers.length} of {customers.length} customers</span>
              )}
            </div>
          </div>
          
          {isLoading ? (
            <Card className="text-center py-12">
              <Spin size="large" tip="Loading customers..." />
            </Card>
          ) : (
            <Card
              className="customer-list-card"
              title={`Customer List (${filteredCustomers.length})`}
              bordered={false}
            >
              <Table
in                dataSource={filteredCustomers}
                rowKey="id"
                locale={{
                  emptyText: 'No customers found'
                }}
                pagination={tableParams.pagination}
                onChange={(pagination) => setTableParams({ pagination: { ...tableParams.pagination, ...pagination } })}
                scroll={{ x: 'max-content' }}
                columns={[
                  {
                    title: 'SL NO',
                    key: 'slNo',
                    render: (text, record, index) => (tableParams.pagination.current - 1) * tableParams.pagination.pageSize + index + 1,
                    width: 80,
                  },
                  {
                    title: 'CUSTOMER NAME',
                    dataIndex: 'name', // ALIGNED FIELD NAME
                    key: 'name',
                    width: 200,
                    render: (text) => (
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-10 w-10 flex items-center justify-center bg-gray-100 rounded-full">
                          <UserOutlined className="text-gray-500" style={{ fontSize: '20px' }} />
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900">{text}</div>
                        </div>
                      </div>
                    ),
                  },
                  {
                    title: 'HOUSE NO./ FLAT NO./ STREET NO.',
                    dataIndex: 'address', // ALIGNED FIELD NAME
                    key: 'address',
                    width: 220,
                  },
                  {
                    title: 'CITY/TOWN/VILLAGE',
                    dataIndex: 'city',
                    key: 'city',
                    width: 150,
                  },
                  {
                    title: 'P.O/DISTRICT',
                    dataIndex: 'district',
                    key: 'district',
                    width: 130,
                  },
                  {
                    title: 'STATE',
                    dataIndex: 'state',
                    key: 'state',
                    width: 130,
                    render: (text) => standardizeState(text),
                  },
                  {
                    title: 'PIN CODE',
                    dataIndex: 'postalCode', // ALIGNED FIELD NAME
                    key: 'postalCode',
                    width: 100,
                  },
                  {
                    title: 'LANDMARK',
                    dataIndex: 'landmark',
                    key: 'landmark',
                    width: 150,
                  },
                  {
                    title: 'MOBILE NO.',
                    dataIndex: 'phone', // ALIGNED FIELD NAME
                    key: 'phone',
                    width: 130,
                  },
                  {
                    title: 'MOBILE NO. 2',
                    dataIndex: 'mobileNumber2',
                    key: 'mobileNumber2',
                    width: 130,
                  },
                  {
                    title: 'SOURCE',
                    dataIndex: 'source',
                    key: 'source',
                    width: 120,
                    render: (text) => text ? <Tag color="blue">{text}</Tag> : '-',
                  },
                  {
                    title: 'Actions',
                    key: 'actions',
                    fixed: 'right',
                    width: 120,
                    render: (text, record) => (
                      <Space>
                        <Tooltip title="Edit customer">
                          <Button
                            type="text"
                            icon={<EditOutlined />}
                            onClick={() => handleEdit(record)}
                            className="text-blue-600 hover:text-blue-800 hover:bg-blue-50"
                          />
                        </Tooltip>
                        <Tooltip title="Delete customer">
                          <Button
                            type="text"
                            icon={<DeleteOutlined />}
                            onClick={() => handleDelete(record.id)}
                            className="text-red-600 hover:text-red-800 hover:bg-red-50"
                          />
                        </Tooltip>
                      </Space>
                    ),
                  },
                ]}
              />
            </Card>
          )}

          {/* Import Modal */}
          <Modal
            title="Import Customers from Excel"
            open={showImportModal}
            onCancel={() => {
              setShowImportModal(false);
              setSelectedFile(null);
            }}
            footer={null}
            width={600}
          >
            <div className="mb-4">
              <p className="text-sm text-gray-600 mb-1">
                Upload an Excel file to import customers.
              </p>
              <Alert
                message="Please use the template to ensure correct formatting."
                description="The first row of your file must contain the exact headers provided in the template file."
                type="info"
                showIcon
                className="mb-4"
              />

              <div className="mt-4">
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Select File
                </label>
                <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md hover:border-gray-400 transition-colors">
                  <div className="space-y-1 text-center">
                    <InboxOutlined style={{ fontSize: '48px' }} className="mx-auto text-gray-400" />
                    <div className="flex text-sm text-gray-600">
                      <label
                        htmlFor="excelFileInput"
                        className="relative cursor-pointer bg-white rounded-md font-medium text-blue-600 hover:text-blue-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-blue-500"
                      >
                        <span>Upload a file</span>
                        <input 
                          id="excelFileInput" 
                          name="excelFileInput" 
                          type="file" 
                          className="sr-only" 
                          onChange={handleFileUpload} 
                          accept=".xlsx, .xls" 
                        />
                      </label>
                      <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-gray-500">XLS, XLSX up to 10MB</p>
                    {selectedFile && (
                      <p className="text-sm text-green-600 mt-2 font-medium">
                        ✓ Selected: {selectedFile.name}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-6 flex justify-end space-x-2">
              <Button
                onClick={() => {
                  setShowImportModal(false);
                  setSelectedFile(null);
                }}
              >
                Cancel
              </Button>
              <Button
                type="primary"
                onClick={handleImportCustomers}
                disabled={!selectedFile || isImporting}
                icon={<ImportOutlined />}
                loading={isImporting}
              >
                {isImporting ? 'Importing...' : 'Import Customers'}
              </Button>
            </div>
          </Modal>

          {/* Update Modal */}
          <Modal
            title="Update Customers from Excel"
            open={showUpdateModal}
            onCancel={() => {
              setShowUpdateModal(false);
              setSelectedFile(null);
            }}
            footer={null}
            width={600}
          >
            <div className="mb-4">
              <p className="text-sm text-gray-600 mb-1">
                Upload an Excel file to update existing customers.
              </p>
              <Alert
                message="Please use the template to ensure correct formatting."
                description="The first row of your file must contain the exact headers provided in the template file. Customers will be matched by 'MOBILE NO.'."
                type="info"
                showIcon
                className="mb-4"
              />

              <div className="mt-4">
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Select File
                </label>
                <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md hover:border-gray-400 transition-colors">
                  <div className="space-y-1 text-center">
                    <InboxOutlined style={{ fontSize: '48px' }} className="mx-auto text-gray-400" />
                    <div className="flex text-sm text-gray-600">
                      <label
                        htmlFor="excelUpdateFileInput"
                        className="relative cursor-pointer bg-white rounded-md font-medium text-blue-600 hover:text-blue-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-blue-500"
                      >
                        <span>Upload a file</span>
                        <input 
                          id="excelUpdateFileInput" 
                          name="excelUpdateFileInput" 
                          type="file" 
                          className="sr-only" 
                          onChange={handleFileUpload} 
                          accept=".xlsx, .xls" 
                        />
                      </label>
                      <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-gray-500">XLS, XLSX up to 10MB</p>
                    {selectedFile && (
                      <p className="text-sm text-green-600 mt-2 font-medium">
                        ✓ Selected: {selectedFile.name}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-6 flex justify-end space-x-2">
              <Button
                onClick={() => {
                  setShowUpdateModal(false);
                  setSelectedFile(null);
                }}
              >
                Cancel
              </Button>
              <Button
                type="primary"
                onClick={handleUpdateCustomers}
                disabled={!selectedFile || isImporting}
                icon={<UserSwitchOutlined />}
                loading={isImporting}
                style={{ backgroundColor: '#faad14', color: 'white', borderColor: '#faad14' }}
              >
                {isImporting ? 'Updating...' : 'Update Customers'}
              </Button>
            </div>
          </Modal>
        </div>
      </div>
    </div>
  );
};

export default CustomerScreen;